-- Portfolio Query 11: Total revenue per part type
-- Purpose: Measure the total revenue generated by each product category
-- Data source: lineitem (transaction-level revenue) joined to part (product category)
-- Method: Calculate revenue using l_extendedprice * (1 - l_discount), then aggregate
--         by part type to identify the highest-performing product categories

SELECT 
    p.p_type AS part_type,
    ROUND(SUM(l.l_extendedprice * (1 - l.l_discount))) AS total_revenue
    FROM lineitem l
    JOIN part p
      ON l.l_partkey = p.p_partkey
    GROUP BY p.p_type
    ORDER BY total_revenue DESC;